<a href="https://colab.research.google.com/github/yamini0809/ML_ICP3/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: a) Using NumPy create random vector of size 15 having only Integers in the range 1-20. 1. Reshape the array to 3 by 5 2. Print array shape. 3. Replace the maxin each row by 0


In [12]:
import numpy as np
# Generate an array of 15 random integers between 1 and 20
a= np.random.randint(low=1, high=21, size=15)
# Reshape the array into a 3x5 matrix
a= a.reshape(3, 5)
print("Array shape:", a.shape)
# Set the maximum value in each row to 0
# `a.argmax(axis=1)` finds the indices of the maximum values along each row
# `np.arange(a.shape[0])` creates an array of indices [0, 1, 2] corresponding to each row
# `a[a.argmax(axis=1), np.arange(a.shape[0])] = 0` sets the maximum values to 0 using advanced indexing
a[a.argmax(axis=1), np.arange(a.shape[0])] = 0
print(a)

Array shape: (3, 5)
[[16 20 12  5 20]
 [ 0  0 11 11  8]
 [18 16  0  8 16]]


Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array


In [3]:
import numpy as np
# Create a 2D array (4x3) with specified integers
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)
#Print the type,shape and datatype of the array
print("Array shape:", b.shape)
print("Array type:", type(b))
print("Array data type:", b.dtype)
print(b)

Array shape: (4, 3)
Array type: <class 'numpy.ndarray'>
Array data type: int32
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


b). Write a program to compute the eigenvalues and right eigenvectors of a given square array given below: [[ 3 -2] [ 1 0]]

In [4]:
import numpy as np
# Create a 2x2 matrix
c = np.array([[3, -2], [1, 0]])
# Compute the eigenvalues and right eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(c)
print("Eigenvalues", eigenvalues)
print("Right eigenvectors:")
print(eigenvectors)

Eigenvalues [2. 1.]
Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


c). Compute the sum of the diagonal element of a given array. [[0 1 2] [3 4 5]]

In [5]:
import numpy as np
d= np.array([[0, 1, 2], [3, 4, 5]])
# Compute the sum of the diagonal elements (trace) of the matrix
sum= np.trace(d)
print("Sum of diagonal elements/TRace:", sum)

Sum of diagonal elements/TRace: 4


d). Write a NumPy program to create a new shape to an array without changing its data.

In [6]:
#Reshape 3x2: [[1 2] [3 4] [5 6]]
import numpy as np
e= np.array([[1, 2], [3, 4], [5, 6]])
# Reshape the matrix to a 2x3 matrix
f= e.reshape((2, 3))
# Print the original array
print("Original array:\n", e)
# Print the reshaped array
print("Reshaped array:\n", f)

Original array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [7]:
#Reshape 2x3: [[1 2 3] [4 5 6]
import numpy as np
g = np.array([[1, 2, 3], [4, 5, 6]])
# Reshape the matrix to a 3x2 matrix
h= g.reshape((3, 2))
# Print the original array
print("Original array:\n", g)
# Print the reshaped array
print("Reshaped array:\n", h)

Original array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
